 - name: Implementing tags
   hosts: all
   tasks:
     - name: install tree
       apt:
         name: tree
         state: present
         update_cache: yes
       tags: tree_installation
     - name: create user
       user:
         name: ramesh
         password: intelliqit
       tags: user_creation
     - name: copy password file
       copy:
         src: /etc/passwd
         dest: /tmp


