  
   - name: create a file and put content in the file
     hosts: all
     tasks:
       - name: create a file
         file:
           name: /home/ubuntu/file100
           state: touch
       - name: place content into file
         copy:
           content: "Intelliqit"
           dest: /home/ubuntu/file100

