  - name: Implementing play scope variables
    hosts: all
    vars:
      - a: tomcat9
      - b: present
      - c: yes
    tasks:
      - name: install the s/w
        apt:
          name: "{{a}}"
          state: "{{b}}"
          update_cache: "{{c}}"
