  
  - name: Configuring jenkins
    hosts: all
    tasks:
      - name: installing java
        apt:
          name: openjdk-11-jdk
          state: present
      - name: installing jenkins
        get_url:
          url: https://get.jenkins.io/war-stable/2.414.1/jenkins.war 
          dest: /home/ubuntu
      - name: restart the jenkins
        shell: java -jar /home/ubuntu/jenkins.war
          


    
