  - name: create users and create files
    hosts: all
    tasks:
      - name: create user
        user:
          name: "{{a}}"
          password: "{{b}}"
          home: "{{c}}"
      - name: create file
        file:
          name: "{{d}}"
          state: "{{e}}"
