 - name: Install s/w's
   hosts: all
   tasks:
     - name: Install s/w
       apt:
         name: "{{item}}"
         state: present
         update_cache: yes
       with_items:
         - tree
         - openjdk-11-jdk
         - maven
