 - name: implementing host scope variable
   hosts: 172.31.40.187
   tasks:
     - name: create user
       user:
         name: "{{a}}"
         password: "{{b}}"
         uid: "{{c}}"
         home: "{{d}}"
         shell: "{{e}}"
         comment: "{{f}}"
